server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    renewalPercentThreshold: 0.49

logging.level:
  com.netflix:
    eureka: OFF
    discovery: OFF
