server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    renewalPercentThreshold: 0.49

# logging properties don't work because not having spring web dependency. I think.
# So have to use logback-spring.xml.
# This property is used by logback-spring.xml
logging.file: /home/jie/project/discovery/discovery.log
